### ISSUE TITLE
plugin seems not to work on newer eclipse/pydev version

### ISSUE THREAD

**Issue by rduivenvoorde** [sourcepole/qgis-remote-debug#4]
I succesfully can use the plugin on the combination Eclipse 3.7.2 and PyDev 2.8.2

But when I installed current eclipse here (Keppler) on debian and installed latest pydev (3.5.0) the plugin fails to stop top at a breakpoint (I used HelloWorld plugin as an example). In the terminal/debug I see:

pydev debugger: warning: trying to add breakpoint to file that does not exist: /home/richard/dev/qgis/git/qgis22/build/output/bin/0 (will have no effect)
Traceback (most recent call last):
  File "/home/richard/.qgis2/python/plugins/remotedebug/pysrc/pydevd.py", line 603, in processNetCommand
    line = int(line)
ValueError: invalid literal for int() with base 10: '/home/richard/.qgis2/python/plugins/HelloWorld/HelloWorld.py'
pydev debugger: warning: trying to add breakpoint to file that does not exist: /home/richard/dev/qgis/git/qgis22/build/output/bin/1 (will have no effect)
Traceback (most recent call last):
  File "/home/richard/.qgis2/python/plugins/remotedebug/pysrc/pydevd.py", line 603, in processNetCommand
    line = int(line)
ValueError: invalid literal for int() with base 10: '/home/richard/.qgis2/python/plugins/HelloWorld/HelloWorld.py'
Unable to Import: false when determining exceptions to break.
Unable to Import: true when determining exceptions to break.

Should this work?

For both I used the option to 'autogenerate' the PYTHONPATH

**Comment by pka** [comment]
Version 0.4.0 has a configurable path for PyDev.
