### ISSUE TITLE
"Debugging Connection failed" with PyDev in eclipse

### ISSUE THREAD

**Issue by jfloviou** [sourcepole/qgis-remote-debug#5]
I've just installed Remote Debug plugin. I start PyDev in eclipse, and launch the Remote Debug.
=> "Debugging Connection failed".

I've added some debug in the code, and it is because _pydev_imps module is missing.

I then figured out that the pydev version in pysrc is an old one (latest release), despite the fact that Remote Debug code depends on _pydev_imps which is only in the latest dev version of pydev.

**Comment by pka** [comment]
Version 0.4.0 has a configurable path for PyDev.
