### ISSUE TITLE
What about letting the user configure the path to its own Eclipse pydevd?

### ISSUE THREAD

**Issue by giohappy** [sourcepole/qgis-remote-debug#6]
Yestaerday I gave a try to remote debug. It failed because there were errors with the pudevd bundled within the pysrc folder.
I removed it and set the PYTHONPATH point to my own pydevd folder and everything worked fine.
I've stripped to remove the other IDEs (Eric and the other), so I'm having a Pydev Debug plugin now. Before trashing Remote Debug I thought we could consider adding the a preferences window to define which debugger to set specific options for each debugger. E.g. for PyDev a path to override its bundled pydevd. With a tiny effort we could alse let the user choose which debugger to activate, instead of using the exceptions to try each debugger in turn...

**Comment by luipir** [comment]
That was my idea for a pull request and one of the subject in the chapter 9 of packt Mastering QGIS.

I though that the plugin is designed for people with limited configuration skill (especially on win where to find pydevd src is not obvious), but this create more problems than advantages.

A flexible configuration can be managed adding a configuration parameters (adding the correct path to pythonpath) and checking it before module import to check if to import the local (to plugin) pydevd module or the version installed with the IDE.

I think would be great adding also configurability about parameters like host and Freeze/not Freeze starting settrace.

**Comment by giohappy** [comment]
Hi Luigi,
you got it right ;)
Could you share your own repo to test your proposal (and hopefully your PR)?

**Comment by luipir** [comment]
unfortunately it's only an idea and I hadn't free time to create it :(

**Comment by pka** [comment]
I've added a basic implementation of your ideas in current master. Could you give me feedback regarding PyDev?

**Comment by pka** [comment]
PyDev successfully tested on Windows. Implemented in version 0.4.0.
