### ISSUE TITLE
should eric6 also work?

### ISSUE THREAD

**Issue by rduivenvoorde** [sourcepole/qgis-remote-debug#7]
I'm looking for a way to use Eric (eric6 is installed) to do the debugging of QGIS3 plugins.

But till now fail to do this with the Remote Debugger plugin

I'm running debian, loaded a plugin and changed Eric's settings to resemble the ones in the Remote Debugger dialog.

After the first (failing) trials, I had a look into the code, and it seemed to me that it tried to connect to port 42424 (instead of 43434 I see in my Eric settings. so I changed that to 42424).
But still not working.

Then I read:
https://github.com/davy39/eric/blob/master/README-passive-debugging.txt
searched for DebugClient.py and copied that dir into the Remote Debugger plugin dir (as I thought that maybe the client code was changed...).
Still no connection.

I'm familiar with pycharm 'remote debugging', but do not get this to work.

Any help or information is appreciated. If this works I think it is worth a blog anyway, because then it's a free way for QGIS plugin devs to actually debug their code when run in QGIS... 

I've also have to confess that this is black magic to me, so any pointers to some information how this works is also very much appreciated.

**Comment by pka** [comment]
It did work with Eric4, but I never tested with a newer version. Maybe @hdus?

**Comment by rduivenvoorde** [comment]
FYI: I've got it to work by adding the dbg_client/DebugClient stuff from eric6 into the plugin and changing a lot of imports (I have to find out if it is possible without all those edits... I had to do a lot of:
"from DebugBase import DebugBase"   to "from .DebugBase import DebugBase".
Have to find out if there is an easier way to make this work.
Will try to do a PR with (I now think) adding an item in the dropdown for eric6

**Comment by rduivenvoorde** [comment]
@pka @hdus see https://github.com/sourcepole/qgis-remote-debug/pull/8

Did the earlier versions work on Windows?

**Comment by pka** [comment]
Thanks!
